### ISSUE TITLE
Script extras/bin/restart-api.sh handling the database event returned with error code 1

### ISSUE THREAD

**Issue by mtmfahath** [maurobonfietti/rest-api-slim-php#60]
Script extras/bin/restart-api.sh handling the database event returned with error code 1 when I run composer database

**Comment by maurobonfietti** [comment]
Hi @mtmfahath 

In order to resolve the problem, please check and follow this steps:


1- First, check that exists the `.env` file. You can use/copy as base this file: `.env.example`

```bash
$ cp .env.example .env
```

2- Edit and complete this configuration file: `.env`. For example:

```
DB_HOSTNAME='yourMySqlHostname'
DB_DATABASE='yourMySqlDatabase'
DB_USERNAME='yourMySqlUsername'
DB_PASSWORD='yourMySqlPassword'
```

3- Check your MySQL connection (using the previous values).

4- If you can connect OK to your MySQL server, try again to run the command: `composer database`.

Also, you can read this [troubleshooting guide](https://github.com/maurobonfietti/rest-api-slim-php/blob/master/TROUBLESHOOTING.md).

Let me know if you need more help.

**Comment by maurobonfietti** [comment]
### Closed.

_**If you have any problem or suggestion, just reopen this issue.**_
