### ISSUE TITLE
Auto documentation

### ISSUE THREAD

**Issue by YohannKIPFER** [maurobonfietti/rest-api-slim-php#72]
Hi,

It is possible with your API to run Swagger documentation automatically ?

Thanks !

Very good job

**Comment by maurobonfietti** [comment]
Interesting question.

I was trying 3 different tools for documentation.

1- Postman:

To be honest, I use Postman (a lot!). I maintain this API, his endpoints and documentation fundamentally with Postman.

Postman has a feature to Publish Docs, so I'm using it.

[View Postman Docs](https://documenter.getpostman.com/view/1915278/RztfwByr?version=latest)


2- Swagger UI:

Postman also has an option to export a collection (to a JSON file).

So, to update the swagger documentation, I use apimatic.io, with the option to Transform API (upload a file or Specify URL), and click on Export Format to Open API/Swagger 3.0 (JSON or YAML).

Then, I move this file to: `./public/docs/swagger.yaml`

[View Swagger Docs](https://rest-api-slim-php.herokuapp.com/docs/index.html)


3- DocGen:

Using [DocGen](https://github.com/thedevsaddam/docgen) to Transform my postman collection to Markdown documentation.

[View DocGen Docs](https://github.com/maurobonfietti/rest-api-slim-php/blob/master/extras/docs/endpoints.md)


----

(The second and third option require some manual work).

I think there must be a better way.

**Anyway, at this moment, in order to keep it simple, I would like continue using only Postman Documenter, because it is really faster and easy.**

Do you know others options?
